# Generated by Django 5.2.6 on 2025-09-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='temp', unique=True),
            preserve_default=False,
        ),
    ]
