# Generated by Django 5.2.6 on 2025-09-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(default='null-1', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
